button_option: stbc_button
comments: 0
late_load: 0
location: content
node_types:
  article: article
  block: block
  gallary: gallary
  news: news
  page: page
option_extras:
  'Google Plus One:plusone': 'Google Plus One:plusone'
  'Facebook Like:fblike': 'Facebook Like:fblike'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Facebook:facebook'',''Twitter:twitter'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  block:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  gallary:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  news:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-d107634e-9716-ba2e-6a89-70fee576fff7
callesi: '0'
